'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import {
  Shield, AlertTriangle, TrendingUp, Brain, ArrowRight,
  CheckCircle, Search, Bell, Zap, Eye, Activity, BarChart2, 
  Users, FileText, Star, ChevronRight
} from 'lucide-react';

const LIVE_ALERTS = [
  { id: 1, severity: 'critical', company: 'PARLE Industries', trigger: 'Parle-G biscuit viral tweet', score: 92, change: '+1,200% volume' },
  { id: 2, severity: 'high', company: 'Signal Advance (SIGL)', trigger: 'Elon Musk "Use Signal" tweet', score: 88, change: '+11,000% price pump' },
  { id: 3, severity: 'medium', company: 'Zoom Tech (ZOOM)', trigger: 'Zoom Video (ZM) product launch hype', score: 64, change: '+48% OTC spike' },
];

const FEATURES = [
  { icon: Search, title: 'Confusion Detector', desc: 'Instantly match corporate names, brands, and ticker symbols to expose identity mismatch before you place an order.', color: 'text-muted-foreground', href: '/detector' },
  { icon: FileText, title: 'News Intelligence', desc: 'Every financial headline scored with sentiment analysis and risk levels, flagging viral news driving wrong tickers.', color: 'text-muted-foreground', href: '/news' },
  { icon: Activity, title: 'Social Trend Monitor', desc: 'Track Reddit, Twitter/X, and YouTube hype spikes in real-time, detecting unnatural volume surges.', color: 'text-muted-foreground', href: '/dashboard' },
  { icon: Brain, title: 'AI Investigations', desc: 'Automated forensic reports generated by AI when a confusion event is detected — root cause, timeline, and investor warning.', color: 'text-muted-foreground', href: '/investigations' },
  { icon: BarChart2, title: 'Market Movement Analyzer', desc: 'Compare actual stock price movement against real news impact to spot pump-like behavior and unjustified rallies.', color: 'text-muted-foreground', href: '/dashboard' },
  { icon: Bell, title: 'Alert Center', desc: 'Multi-severity alerts the moment a confusion signal is detected across any data source.', color: 'text-muted-foreground', href: '/alerts' },
];

const STATS = [
  { label: 'Incidents Detected', value: '2,847', icon: AlertTriangle },
  { label: 'Companies Monitored', value: '18,400+', icon: Eye },
  { label: 'News Articles Processed', value: '1.2M+', icon: FileText },
  { label: 'Detection Accuracy', value: '94.7%', icon: CheckCircle },
];

const BLOGS = [
  { slug: 'why-did-parle-industries-rally-after-melody-went-viral', title: 'Why Did Parle Industries Rally After Melody Went Viral?', category: 'Market Confusion Cases', risk: 'critical', time: '4 min read', date: 'Jun 1, 2026' },
  { slug: 'signal-app-vs-signal-advance-the-11000-ticker-symbol-catastrophe', title: 'Signal App vs Signal Advance: The 11,000% Ticker Catastrophe', category: 'Misinformation Analysis', risk: 'high', time: '5 min read', date: 'May 31, 2026' },
  { slug: 'zoom-video-vs-zoom-technologies-the-otc-name-mistake', title: 'Zoom Video vs Zoom Technologies — The OTC Name Mistake', category: 'Stock Analysis', risk: 'medium', time: '3 min read', date: 'May 28, 2026' },
];

const severityStyles: Record<string, string> = {
  critical: 'text-destructive bg-destructive/10 border border-destructive/25',
  high: 'text-orange-400 bg-orange-400/10 border border-orange-400/25',
  medium: 'text-warning bg-warning/10 border border-warning/25',
  low: 'text-success bg-success/10 border border-success/25',
};

const riskDot: Record<string, string> = {
  critical: 'bg-destructive',
  high: 'bg-orange-400',
  medium: 'bg-warning',
  low: 'bg-success',
};

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.08, duration: 0.5 },
  }),
};

export default function LandingPage() {
  const [ticker, setTicker] = useState(0);

  useEffect(() => {
    const t = setInterval(() => setTicker((p) => (p + 1) % LIVE_ALERTS.length), 4000);
    return () => clearInterval(t);
  }, []);

  const active = LIVE_ALERTS[ticker];

  return (
    <div className="relative flex flex-col">

      {/* ── HERO ─────────────────────────────────────────────────────────── */}
      <section className="relative min-h-screen flex flex-col items-center justify-center text-center px-4 pt-24 pb-32 overflow-hidden bg-grid-pattern">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-muted rounded-full blur-[140px] pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[300px] bg-muted rounded-full blur-[120px] pointer-events-none" />

        <div className="mb-8 inline-flex items-center gap-2.5 px-4 py-2 rounded-full border border-border bg-card/80 text-xs font-semibold text-muted-foreground shadow-lg glass">
          <span className={`inline-flex h-2 w-2 rounded-full animate-ping ${riskDot[active.severity]}`} />
          <span className={`capitalize font-bold ${severityStyles[active.severity].split(' ')[0]}`}>{active.severity}</span>
          <span className="text-muted-foreground">—</span>
          <span className="text-foreground">{active.company}</span>
          <span className="text-muted-foreground hidden sm:inline">·</span>
          <span className="hidden sm:inline text-muted-foreground">{active.change}</span>
        </div>

        <motion.h1 custom={0} initial="hidden" animate="visible" variants={fadeUp} className="max-w-4xl text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight leading-tight text-foreground">
          Detect Market Confusion <span className="text-muted-foreground">Before It Costs You Money</span>
        </motion.h1>

        <motion.p custom={1} initial="hidden" animate="visible" variants={fadeUp} className="mt-6 max-w-xl text-base sm:text-lg text-muted-foreground leading-relaxed">
          AI-powered detection of stock misinformation, company identity confusion, and abnormal market reactions — built for retail investors and traders, analysts, and compliance teams.
        </motion.p>

        <motion.div custom={2} initial="hidden" animate="visible" variants={fadeUp} className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-3">
          <Link href="/dashboard" className="group flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-primary-foreground text-sm font-bold hover:bg-primary/90 transition-all shadow-[0_0_25px_rgba(0,0,0,0.1)]">
            <Zap className="w-4 h-4" />
            Try Live Demo
            <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
          </Link>
          <Link href="/investigations" className="flex items-center gap-2 px-6 py-3 rounded-xl border border-border text-muted-foreground text-sm font-semibold hover:text-foreground hover:border-muted-foreground transition-all">
            <Shield className="w-4 h-4" />
            View Recent Alerts
          </Link>
        </motion.div>

        <motion.div custom={3} initial="hidden" animate="visible" variants={fadeUp} className="mt-14 flex flex-wrap items-center justify-center gap-6 text-xs text-muted-foreground font-medium">
          {['Real-time AI Analysis', 'Zero Setup Required', 'No Financial Advice', 'Privacy-first Architecture'].map((t) => (
            <span key={t} className="flex items-center gap-1.5"><CheckCircle className="w-3.5 h-3.5" />{t}</span>
          ))}
        </motion.div>
      </section>

      {/* ── LIVE ALERT PREVIEW ───────────────────────────────────────────── */}
      <section className="px-4 sm:px-6 lg:px-8 py-20 max-w-7xl mx-auto w-full">
        <div className="mb-10 text-center">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-border text-xs font-semibold text-muted-foreground uppercase tracking-wider">
            <span className="h-2 w-2 rounded-full bg-destructive animate-ping" />Live Alert Feed
          </span>
          <h2 className="mt-4 text-2xl sm:text-3xl font-bold text-foreground tracking-tight">Recent Confusion Events</h2>
          <p className="mt-3 text-muted-foreground text-sm max-w-lg mx-auto">These are real historical cases where retail investors bought the wrong company due to brand name or ticker-symbol confusion.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {LIVE_ALERTS.map((alert, i) => (
            <motion.div key={alert.id} custom={i} initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeUp} className="relative flex flex-col gap-4 p-5 rounded-2xl bg-card/80 border border-border glass-panel-hover group">
              <div className={`absolute top-4 right-4 text-[10px] font-black px-2 py-0.5 rounded-full ${severityStyles[alert.severity]}`}>{alert.severity}</div>
              <div className="flex items-start gap-3">
                <div className={`p-2 rounded-xl ${severityStyles[alert.severity].split(' ').slice(1).join(' ')}`}>
                  <AlertTriangle className={`w-4 h-4 ${severityStyles[alert.severity].split(' ')[0]}`} />
                </div>
                <div>
                  <p className={`text-[10px] font-bold uppercase tracking-widest ${severityStyles[alert.severity].split(' ')[0]}`}>{alert.severity}</p>
                  <p className="mt-0.5 text-sm font-bold text-foreground leading-snug">{alert.company}</p>
                </div>
              </div>
              <div className="space-y-1.5 text-xs text-muted-foreground">
                <p><span className="text-muted-foreground/70 font-semibold">Trigger: </span>{alert.trigger}</p>
                <p><span className="text-muted-foreground/70 font-semibold">Market Impact: </span><span className="text-warning font-semibold">{alert.change}</span></p>
              </div>
              <Link href="/dashboard" className="text-[11px] font-bold text-foreground flex items-center gap-1 hover:gap-2 transition-all mt-auto">Investigate <ArrowRight className="w-3.5 h-3.5" /></Link>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── FEATURES ─────────────────────────────────────────────────────── */}
      <section className="px-4 sm:px-6 lg:px-8 py-20 max-w-7xl mx-auto w-full">
        <div className="mb-12 text-center pt-20">
          <span className="inline-block px-3 py-1 rounded-full border border-border text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">6 detection tools</span>
          <h2 className="text-2xl sm:text-3xl font-bold text-foreground tracking-tight">Every Tool You Need to Stay Safe</h2>
          <p className="mt-3 text-muted-foreground text-sm max-w-lg mx-auto">A complete financial intelligence platform for retail investors, institutional analysts, and market regulators.</p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 items-stretch max-w-[1100px] mx-auto">
          {FEATURES.map((f, i) => {
            const Icon = f.icon;
            return (
              <motion.div key={f.title} custom={i} initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeUp} className="flex flex-col gap-4 p-6 rounded-2xl bg-card/80 border border-border glass-panel-hover">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center bg-muted border border-border"><Icon className={`w-5 h-5 ${f.color}`} /></div>
                <div>
                  <h3 className="text-sm font-bold text-foreground">{f.title}</h3>
                  <p className="mt-1.5 text-xs text-muted-foreground leading-relaxed">{f.desc}</p>
                </div>
                <Link href={f.href} className={`text-[11px] font-bold mt-auto flex items-center gap-1 hover:gap-2 transition-all`}>Explore <ChevronRight className="w-3.5 h-3.5" /></Link>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* ── STATS ────────────────────────────────────────────────────────── */}
      <section className="px-4 sm:px-6 lg:px-8 py-12 w-full border-y border-border bg-muted/30">
        <div className="max-w-7xl mx-auto grid grid-cols-2 lg:grid-cols-4 gap-6">
          {STATS.map((s, i) => {
            const Icon = s.icon;
            return (
              <motion.div key={s.label} custom={i} initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeUp} className="flex flex-col items-center text-center gap-3 p-6 rounded-2xl bg-card/80 border border-border glass">
                <Icon className="w-6 h-6 text-muted-foreground" />
                <p className="text-3xl font-black text-foreground tracking-tight">{s.value}</p>
                <p className="text-xs text-muted-foreground font-semibold">{s.label}</p>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* ── BLOG PREVIEW ─────────────────────────────────────────────────── */}
      <section className="px-4 sm:px-6 lg:px-8 py-20 max-w-7xl mx-auto w-full">
        <div className="flex items-end justify-between mb-10">
          <div>
            <span className="inline-block px-3 py-1 rounded-full border border-border text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">Research Hub</span>
            <h2 className="text-2xl sm:text-3xl font-bold text-foreground tracking-tight">AI-Powered Investigations</h2>
          </div>
          <Link href="/blog" className="hidden sm:flex items-center gap-1.5 text-xs font-bold text-foreground hover:gap-2.5 transition-all">All Articles <ArrowRight className="w-3.5 h-3.5" /></Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {BLOGS.map((b, i) => (
            <motion.div key={b.slug} custom={i} initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeUp}>
              <Link href={`/blog/${b.slug}`} className="group flex flex-col gap-4 p-5 h-full rounded-2xl bg-card/80 border border-border glass-panel-hover">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">{b.category}</span>
                  <span className={`text-[10px] font-black uppercase px-2 py-0.5 rounded-full ${severityStyles[b.risk]}`}>{b.risk}</span>
                </div>
                <h3 className="text-sm font-bold text-foreground leading-snug group-hover:text-foreground/80 transition-colors">{b.title}</h3>
                <div className="mt-auto flex items-center gap-3 text-[10px] text-muted-foreground font-medium">
                  <Star className="w-3 h-3" />
                  <span>{b.time}</span><span>·</span><span>{b.date}</span>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── CTA BANNER ───────────────────────────────────────────────────── */}
      <section className="px-4 sm:px-6 lg:px-8 py-24 max-w-7xl mx-auto w-full">
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }} className="relative flex flex-col items-center text-center gap-6 p-12 rounded-3xl bg-card/80 border border-border glass-panel overflow-hidden">
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none"><div className="w-[500px] h-[200px] bg-muted rounded-full blur-[80px]" /></div>
          <div className="relative">
            <div className="w-12 h-12 mx-auto mb-4 rounded-2xl bg-muted border border-border flex items-center justify-center"><Shield className="w-6 h-6 text-foreground" /></div>
            <h2 className="text-2xl sm:text-3xl font-bold text-foreground tracking-tight">Start Protecting Your Portfolio Today</h2>
            <p className="mt-3 text-muted-foreground text-sm max-w-lg mx-auto">Join thousands of investors and analysts who rely on TickerGuard AI to validate trades before confusion costs them money.</p>
          </div>
          <div className="relative flex flex-col sm:flex-row items-center justify-center gap-3">
            <Link href="/dashboard" className="group flex items-center gap-2 px-8 py-3.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 transition-all shadow-[0_0_30px_rgba(0,0,0,0.1)]">Open Live Dashboard <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" /></Link>
            <Link href="/pricing" className="flex items-center gap-2 px-8 py-3.5 rounded-xl border border-border text-muted-foreground text-sm font-semibold hover:text-foreground transition-all">View Pricing Plans</Link>
          </div>
          <p className="relative text-[10px] text-muted-foreground font-medium">No credit card required · Free Starter tier available · Vercel-deployed</p>
        </motion.div>
      </section>

    </div>
  );
}


