'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { Shield, Search, FileText, TrendingUp, Brain, Zap, ArrowRight, Radio, Bell, BarChart2 } from 'lucide-react';

const FEATURES = [
  { icon: Search, title: 'Confusion Detector', desc: 'Instantly match corporate names, brands, and ticker symbols to expose identity mismatch before you place an order. Powered by Levenshtein distance and AI scoring.', color: 'text-muted-foreground', href: '/detector' },
  { icon: FileText, title: 'News Intelligence Feed', desc: 'Every financial headline scored with sentiment analysis and risk levels, flagging viral news driving wrong tickers. Real-time monitoring across 1000+ sources.', color: 'text-muted-foreground', href: '/news' },
  { icon: BarChart2, title: 'Market Movement Analyzer', desc: 'Compare actual stock price movement against real news impact to spot pump-like behavior and unjustified rallies. Recharts-powered visualizations.', color: 'text-muted-foreground', href: '/dashboard' },
  { icon: Brain, title: 'AI Investigation Engine', desc: 'Automated forensic reports generated by AI when a confusion event is detected — root cause, timeline, affected companies, and investor warning.', color: 'text-muted-foreground', href: '/investigations' },
  { icon: Radio, title: 'Social Media Monitor', desc: 'Track Reddit, Twitter/X, and YouTube hype spikes in real-time, detecting unnatural volume surges that indicate confusion-based buying.', color: 'text-muted-foreground', href: '/dashboard' },
  { icon: Bell, title: 'Alert Center', desc: 'Multi-severity alerts (Low to Critical) triggered the moment a confusion signal is detected across any data source.', color: 'text-muted-foreground', href: '/alerts' },
];

export default function FeaturesPage() {
  return (
    <div className="relative flex flex-col">
      <section className="relative min-h-[60vh] flex flex-col items-center justify-center text-center px-4 pt-80 pb-16 overflow-hidden bg-grid-pattern">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-muted rounded-full blur-[140px] pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[300px] bg-muted rounded-full blur-[120px] pointer-events-none" />

        <div className="relative">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-border text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-6">6 detection tools</span>
          <h1 className="max-w-4xl text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight leading-tight text-foreground">Every Tool You Need to <span className="text-muted-foreground">Stay Safe</span></h1>
          <p className="mt-6 max-w-xl text-base sm:text-lg text-muted-foreground leading-relaxed">A complete financial intelligence platform for retail investors, institutional analysts, and market regulators.</p>
          <div className="mt-8 flex flex-col sm:flex-row items-center gap-4">
            <Link href="/dashboard" className="flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-primary-foreground text-sm font-bold hover:bg-primary/90 transition shadow-[0_0_25px_rgba(0,0,0,0.1)]">
              <Zap className="w-4 h-4" />Try Live Demo<ArrowRight className="w-4 h-4" />
            </Link>
            <Link href="/pricing" className="flex items-center gap-2 px-6 py-3 rounded-xl border border-border text-muted-foreground text-sm font-semibold hover:text-foreground hover:border-muted-foreground transition">View Pricing</Link>
          </div>
        </div>
      </section>

      <section className="px-4 sm:px-6 lg:px-8 py-24 max-w-7xl mx-auto w-full">
        <div className="max-w-[1100px] mx-auto grid grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-8">
          {FEATURES.map((f, i) => {
            const Icon = f.icon;
            return (
              <motion.div key={f.title} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}>
                <Link href={f.href} className={`flex flex-col gap-4 p-6 rounded-2xl bg-card border border-border hover:bg-muted transition-all group`}>
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center bg-muted border border-border"><Icon className={`w-5 h-5 ${f.color}`} /></div>
                  <div>
                    <h3 className="text-sm font-bold text-foreground group-hover:text-foreground/80 transition-colors">{f.title}</h3>
                    <p className="mt-1.5 text-xs text-muted-foreground leading-relaxed">{f.desc}</p>
                  </div>
                  <span className={`text-[11px] font-bold mt-auto flex items-center gap-1 group-hover:gap-2 transition-all`}>Explore <ArrowRight className="w-3.5 h-3.5" /></span>
                </Link>
              </motion.div>
            );
          })}
        </div>
      </section>
    </div>
  );
}
