'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { Shield, Search, FileText, TrendingUp, Brain, Zap, ArrowRight, Radio, Bell } from 'lucide-react';

const FEATURES = [
  {
    icon: Search,
    title: 'Company Identity Detector',
    desc: 'Instantly match corporate names, brands, and ticker symbols to expose identity mismatch before you place an order. Powered by Levenshtein distance and AI scoring.',
    color: 'text-[#00E5A8]',
    bg: 'bg-[#00E5A8]/10',
    border: 'border-[#00E5A8]/20',
    href: '/dashboard/detector',
  },
  {
    icon: FileText,
    title: 'News Intelligence Feed',
    desc: 'Every financial headline scored with sentiment analysis and risk levels, flagging viral news driving wrong tickers. Real-time monitoring across 1000+ sources.',
    color: 'text-blue-400',
    bg: 'bg-blue-400/10',
    border: 'border-blue-400/20',
    href: '/dashboard/news',
  },
  {
    icon: TrendingUp,
    title: 'Market Movement Analyzer',
    desc: 'Compare actual stock price movement against real news impact to spot pump-like behavior and unjustified rallies. Recharts-powered visualizations.',
    color: 'text-[#FF5A5A]',
    bg: 'bg-[#FF5A5A]/10',
    border: 'border-[#FF5A5A]/20',
    href: '/dashboard',
  },
  {
    icon: Brain,
    title: 'AI Investigation Engine',
    desc: 'Automated forensic reports generated by AI when a confusion event is detected — root cause, timeline, affected companies, and investor warning.',
    color: 'text-[#FFC857]',
    bg: 'bg-[#FFC857]/10',
    border: 'border-[#FFC857]/20',
    href: '/dashboard/investigations',
  },
  {
    icon: Radio,
    title: 'Social Media Monitor',
    desc: 'Track Reddit, Twitter/X, and YouTube hype spikes in real-time, detecting unnatural volume surges that indicate confusion-based buying.',
    color: 'text-purple-400',
    bg: 'bg-purple-400/10',
    border: 'border-purple-400/20',
    href: '/dashboard',
  },
  {
    icon: Bell,
    title: 'Alert Center',
    desc: 'Multi-severity alerts (Low to Critical) triggered the moment a confusion signal is detected across any data source.',
    color: 'text-orange-400',
    bg: 'bg-orange-400/10',
    border: 'border-orange-400/20',
    href: '/dashboard/alerts',
  },
];

export default function FeaturesPage() {
  return (
    <div className="relative flex flex-col">
      <section className="relative min-h-[60vh] flex flex-col items-center justify-center text-center px-4 pt-24 pb-16 overflow-hidden bg-grid-pattern">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-[#00E5A8]/6 rounded-full blur-[140px] pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[300px] bg-[#FF5A5A]/5 rounded-full blur-[120px] pointer-events-none" />

        <div className="relative">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-[#262626] text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-6">
            <Shield className="w-3.5 h-3.5 text-[#00E5A8]" />
            Intelligence Suite
          </span>
          <h1 className="max-w-4xl text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight leading-tight text-white">
            Every Tool You Need to{' '}
            <span className="text-[#00E5A8]">Stay Safe</span>
          </h1>
          <p className="mt-6 max-w-xl text-base sm:text-lg text-zinc-400 leading-relaxed">
            A complete financial intelligence platform for retail investors, institutional analysts, and market regulators.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row items-center gap-4">
            <Link
              href="/dashboard"
              className="flex items-center gap-2 px-6 py-3 rounded-xl bg-[#00E5A8] text-black text-sm font-bold shadow-[0_0_25px_rgba(0,229,168,0.25)] hover:bg-[#00E5A8]/90 transition"
            >
              <Zap className="w-4 h-4" />
              Try Live Demo
              <ArrowRight className="w-4 h-4" />
            </Link>
            <Link
              href="/pricing"
              className="flex items-center gap-2 px-6 py-3 rounded-xl border border-[#262626] text-zinc-300 text-sm font-semibold hover:border-zinc-600 hover:text-white transition"
            >
              View Pricing
            </Link>
          </div>
        </div>
      </section>

      <section className="px-4 sm:px-6 lg:px-8 py-20 max-w-7xl mx-auto w-full">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((f, i) => {
            const Icon = f.icon;
            return (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.08 }}
              >
                <Link
                  href={f.href}
                  className={`flex flex-col gap-4 p-6 rounded-2xl bg-[#111111] border ${f.border} hover:bg-[#161616] hover:border-[#262626] transition-all group`}
                >
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${f.bg} border ${f.border}`}>
                    <Icon className={`w-5 h-5 ${f.color}`} />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-white group-hover:text-[#00E5A8] transition-colors">{f.title}</h3>
                    <p className="mt-1.5 text-xs text-zinc-500 leading-relaxed">{f.desc}</p>
                  </div>
                  <span className={`text-[11px] font-bold ${f.color} flex items-center gap-1 group-hover:gap-2 transition-all mt-auto`}>
                    Explore <ArrowRight className="w-3.5 h-3.5" />
                  </span>
                </Link>
              </motion.div>
            );
          })}
        </div>
      </section>
    </div>
  );
}
